//USER ROLES FOR THE APPLICATION

//DEFAULT ROLES (DEFAULT USER AND SUPERADMIN)
export const DEFAULT_ROLES = ['USER', 'SUPERADMIN'];

//HERE WE CAN ADD THE CUSTOM ROLES FOR THIS PROJECT
//FOR EXAMPLE ["WAITER", "CHEF", "MANAGER"]
export const PROJECT_ROLES: string[] = ["WAITER", "CHEF", "MANAGER"]; 
